# Generated by Django 5.1.6 on 2025-05-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CityMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ftp/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='reported', max_length=20)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('identify_object', models.ImageField(upload_to='cropped_objects/')),
                ('reason', models.TextField(blank=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('central', 'Central')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
        ),
    ]
