# Generated by Django 5.2.1 on 2025-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymonitoring',
            name='ward',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
